nohup: ignoring input
Args in experiment:
Namespace(activation='gelu', anomaly_ratio=0.25, batch_size=32, c_out=151, checkpoints='./checkpoints/', d_ff=2048, d_layers=1, d_model=128, data='custom', data_path='pems03_all_common_flow.csv', dec_in=151, des='Exp', devices='0,1,2,3', distil=True, dropout=0, e_layers=2, embed='timeF', enc_in=151, factor=3, features='M', freq='h', gpu=0, inverse=False, is_training=1, itr=1, label_len=48, learning_rate=0.0005, loss='MSE', lradj='type3', mask_rate=0.25, model='Autoformer', model_id='traffic_168_96', moving_avg=25, n_heads=8, num_kernels=6, num_workers=10, output_attention=False, p_hidden_dims=[128, 128], p_hidden_layers=2, patience=5, pred_len=16800, root_path='../../data/pems/', seasonal_patterns='Monthly', seq_len=16800, target='OT', task_name='long_term_forecast', top_k=5, train_epochs=200, use_amp=False, use_gpu=True, use_multi_gpu=False)
Use GPU: cuda:0
>>>>>>>start training : long_term_forecast_traffic_168_96_Autoformer_custom_ftM_sl16800_ll48_pl16800_dm128_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0>>>>>>>>>>>>>>>>>>>>>>>>>>
t	iters: 100, epoch: 1 | test 441597
Traceback (most recent call last):
  File "run.py"	iters: 200, epoch: 1 | loss: 0.3112487
	speed: 2.9989s/iter; left time: 224317.5690s
	iters: 300, epoch: 1 | loss: 0.2812156
	speed: 2.8025s/iter; left time: 209348.3501s
Epoch: 1 cost time: 1046.6261234283447
Traceback (most recent call last):
  File "run.py", line 147, in <module>
    exp.train(setting)
  File "/g/data/hn98/du/exlts/dddtimesnet/exp/exp_long_term_forecasting.py", line 206, in train
    vali_loss = self.vali(vali_data, vali_loader, criterion)
  File "/g/data/hn98/du/exlts/dddtimesnet/exp/exp_long_term_forecasting.py", line 67, in vali
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
  File "/jobfs/115974024.gadi-pbs/timesnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/g/data/hn98/du/exlts/dddtimesnet/models/Autoformer.py", line 147, in forward
    dec_out = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
  File "/g/data/hn98/du/exlts/dddtimesnet/models/Autoformer.py", line 103, in forecast
    enc_out, attns = self.encoder(enc_out, attn_mask=None)
  File "/jobfs/115974024.gadi-pbs/timesnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/g/data/hn98/du/exlts/dddtimesnet/layers/Autoformer_EncDec.py", line 131, in forward
    x, attn = attn_layer(x, attn_mask=attn_mask)
  File "/jobfs/115974024.gadi-pbs/timesnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/g/data/hn98/du/exlts/dddtimesnet/layers/Autoformer_EncDec.py", line 96, in forward
    new_x, attn = self.attention(
  File "/jobfs/115974024.gadi-pbs/timesnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/g/data/hn98/du/exlts/dddtimesnet/layers/AutoCorrelation.py", line 155, in forward
    out, attn = self.inner_correlation(
  File "/jobfs/115974024.gadi-pbs/timesnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/g/data/hn98/du/exlts/dddtimesnet/layers/AutoCorrelation.py", line 123, in forward
    V = self.time_delay_agg_inference(values.permute(0, 2, 3, 1).contiguous(), corr).permute(0, 3, 1, 2)
  File "/g/data/hn98/du/exlts/dddtimesnet/layers/AutoCorrelation.py", line 61, in time_delay_agg_inference
    init_index = torch.arange(length).unsqueeze(0).unsqueeze(0).unsqueeze(0).repeat(batch, head, channel, 1).cuda()
  File "/jobfs/115974024.gadi-pbs/timesnet/lib/python3.8/site-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
