Args in experiment:
Namespace(activation='gelu', anomaly_ratio=0.25, batch_size=16, c_out=103, checkpoints='./checkpoints/', d_ff=512, d_layers=1, d_model=512, data='custom', data_path='pems05_all_common_flow.csv', dec_in=103, des='Exp', devices='0,1,2,3', distil=True, dropout=0, e_layers=4, embed='timeF', enc_in=103, factor=3, features='M', freq='h', gap_day=730, gpu=0, inverse=False, is_training=1, itr=1, label_len=48, learning_rate=0.001, loss='MSE', lradj='type1', mask_rate=0.25, model='iTransformer', model_id='pems05_all_96_720', moving_avg=25, n_heads=8, num_kernels=6, num_workers=10, output_attention=False, p_hidden_dims=[128, 128], p_hidden_layers=2, patience=3, pred_len=720, root_path='../../data/pems/', samle_rate=0.1, sample_seed=7, seasonal_patterns='Monthly', seq_len=96, target='OT', task_name='long_term_forecast', top_k=5, train_epochs=10, train_seed=2024, use_amp=False, use_gpu=False, use_multi_gpu=False)
Use CPU
>>>>>>>start training : long_term_forecast_pems05_all_96_720_iTransformer_custom_ftM_sl96_ll48_pl720_dm512_nh8_el4_dl1_df512_fc3_ebtimeF_dtTrue_srate0.1_sseed7_trainseed2024_gap730_Exp_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 547735
Traceback (most recent call last):
  File "run.py", line 159, in <module>
    exp.train(setting)
  File "/g/data/hn98/du/exlts/ddd2/exp/exp_long_term_forecasting.py", line 84, in train
    train_data, train_loader = self._get_data(flag='train')
  File "/g/data/hn98/du/exlts/ddd2/exp/exp_long_term_forecasting.py", line 31, in _get_data
    data_set, data_loader = data_provider(self.args, flag)
  File "/g/data/hn98/du/exlts/ddd2/data_provider/data_factory.py", line 118, in data_provider
  File "/g/data/hn98/du/exlts/ddd2/data_provider/data_factory.py", line 25, in create_dataloader
  File "/jobfs/116751235.gadi-pbs/timesnet/lib/python3.8/site-packages/torch/random.py", line 36, in manual_seed
    torch.cuda.manual_seed_all(seed)
  File "/jobfs/116751235.gadi-pbs/timesnet/lib/python3.8/site-packages/torch/cuda/random.py", line 113, in manual_seed_all
    _lazy_call(cb)
  File "/jobfs/116751235.gadi-pbs/timesnet/lib/python3.8/site-packages/torch/cuda/__init__.py", line 117, in _lazy_call
    _queued_calls.append((callable, traceback.format_stack()))
  File "/jobfs/116751235.gadi-pbs/timesnet/lib/python3.8/traceback.py", line 197, in format_stack
    return format_list(extract_stack(f, limit=limit))
  File "/jobfs/116751235.gadi-pbs/timesnet/lib/python3.8/traceback.py", line 211, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "/jobfs/116751235.gadi-pbs/timesnet/lib/python3.8/traceback.py", line 366, in extract
    f.line
  File "/jobfs/116751235.gadi-pbs/timesnet/lib/python3.8/traceback.py", line 288, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "/jobfs/116751235.gadi-pbs/timesnet/lib/python3.8/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/jobfs/116751235.gadi-pbs/timesnet/lib/python3.8/site-packages/torch/_fx/graph_module.py", line 27, in patched_getline
    return _orig_getlines(*args, **kwargs)
  File "/jobfs/116751235.gadi-pbs/timesnet/lib/python3.8/linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "/jobfs/116751235.gadi-pbs/timesnet/lib/python3.8/linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "/jobfs/116751235.gadi-pbs/timesnet/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 751: invalid continuation byte
